# import data and dependency

In [6]:
import numpy as np
import pandas as pd

In [42]:
prices = pd.read_csv('data/sell_prices.csv')
calendar = pd.read_csv('data/calendar.csv')
sales = pd.read_csv('data/sales_train_validation.csv')
sample_submission = pd.read_csv('data/sample_submission.csv')

# data cleaning

In [8]:
prices.head()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [15]:
len(prices.item_id)

3049

In [41]:
len(pd.unique(prices.store_id + prices.item_id))

30490

In [18]:
prices.wm_yr_wk.max() - prices.wm_yr_wk.min()

520

In [16]:
sales.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4

In [19]:
len(sales.id.unique())

30490

In [20]:
sample_submission.head()

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,HOBBIES_1_001_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,HOBBIES_1_002_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,HOBBIES_1_004_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,HOBBIES_1_005_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
len(sample_submission.id.unique())

60980

In [23]:
set(sample_submission.id) - set(sales.id)

{'FOODS_2_265_CA_3_evaluation',
 'HOUSEHOLD_1_539_TX_1_evaluation',
 'FOODS_1_146_CA_1_evaluation',
 'HOUSEHOLD_1_195_WI_2_evaluation',
 'FOODS_2_389_CA_2_evaluation',
 'FOODS_1_166_CA_2_evaluation',
 'FOODS_3_680_TX_3_evaluation',
 'FOODS_2_030_WI_2_evaluation',
 'FOODS_3_514_TX_3_evaluation',
 'FOODS_2_229_WI_2_evaluation',
 'FOODS_1_168_CA_2_evaluation',
 'FOODS_2_140_CA_2_evaluation',
 'HOBBIES_1_134_TX_2_evaluation',
 'HOBBIES_1_111_CA_1_evaluation',
 'FOODS_2_336_WI_1_evaluation',
 'FOODS_2_323_WI_1_evaluation',
 'HOUSEHOLD_1_039_CA_3_evaluation',
 'HOUSEHOLD_2_505_TX_3_evaluation',
 'FOODS_3_114_TX_3_evaluation',
 'HOBBIES_1_070_WI_3_evaluation',
 'FOODS_3_469_CA_4_evaluation',
 'HOBBIES_1_017_CA_1_evaluation',
 'HOUSEHOLD_1_055_CA_1_evaluation',
 'FOODS_3_415_CA_4_evaluation',
 'HOUSEHOLD_2_273_TX_2_evaluation',
 'FOODS_3_226_CA_1_evaluation',
 'HOUSEHOLD_1_368_CA_3_evaluation',
 'FOODS_3_761_WI_2_evaluation',
 'HOUSEHOLD_1_212_WI_3_evaluation',
 'FOODS_3_729_WI_1_evaluation',
 'FOODS_1_117_CA_1_evaluation',
 'FOODS_3_695_WI_2_evaluation',
 'HOUSEHOLD_2_072_WI_3_evaluation',
 'FOODS_3_080_CA_2_evaluation',
 'FOODS_3_716_WI_2_evaluation',
 'FOODS_2_077_TX_1_evaluation',
 'HOUSEHOLD_2_191_CA_4_evaluation',
 'HOUSEHOLD_2_475_TX_2_evaluation',
 'FOODS_2_031_CA_4_evaluation',
 'FOODS_3_255_TX_2_evaluation',
 'HOUSEHOLD_1_185_TX_1_evaluation',
 'FOODS_1_127_WI_2_evaluation',
 'FOODS_3_135_TX_1_evaluation',
 'HOUSEHOLD_2_079_CA_2_evaluation',
 'HOUSEHOLD_2_034_CA_4_evaluation',
 'FOODS_2_127_CA_3_evaluation',
 'HOUSEHOLD_1_508_WI_1_evaluation',
 'FOODS_3_216_WI_1_evaluation',
 'HOUSEHOLD_1_274_WI_1_evaluation',
 'HOBBIES_1_123_CA_2_evaluation',
 'HOUSEHOLD_2_234_TX_1_evaluation',
 'HOUSEHOLD_2_465_CA_4_evaluation',
 'FOODS_1_109_CA_4_evaluation',
 'FOODS_3_392_WI_1_evaluation',
 'HOBBIES_2_116_CA_4_evaluation',
 'HOBBIES_1_106_CA_1_evaluation',
 'HOBBIES_2_107_CA_2_evaluation',
 'FOODS_3_629_WI_2_evaluation',
 'HOUSEHOLD_1_164_CA_1_evaluation',
 'HOBBIES_1_270_CA_4_evaluation',
 'HOBBIES_1_025_CA_1_evaluation',
 'HOBBIES_1_226_CA_3_evaluation',
 'HOBBIES_1_340_TX_3_evaluation',
 'HOUSEHOLD_1_055_WI_1_evaluation',
 'HOUSEHOLD_1_251_WI_2_evaluation',
 'HOBBIES_1_251_CA_3_evaluation',
 'FOODS_2_339_TX_3_evaluation',
 'HOBBIES_2_147_WI_3_evaluation',
 'HOUSEHOLD_1_484_WI_2_evaluation',
 'HOUSEHOLD_1_252_WI_3_evaluation',
 'FOODS_2_230_CA_3_evaluation',
 'HOUSEHOLD_2_056_TX_1_evaluation',
 'HOUSEHOLD_2_001_WI_1_evaluation',
 'HOUSEHOLD_1_244_WI_3_evaluation',
 'HOBBIES_1_044_CA_3_evaluation',
 'HOBBIES_1_058_CA_1_evaluation',
 'FOODS_3_356_TX_3_evaluation',
 'FOODS_2_268_CA_2_evaluation',
 'FOODS_3_145_CA_4_evaluation',
 'FOODS_3_569_TX_3_evaluation',
 'FOODS_1_151_TX_2_evaluation',
 'FOODS_1_068_TX_1_evaluation',
 'HOUSEHOLD_1_039_TX_3_evaluation',
 'FOODS_1_052_CA_3_evaluation',
 'HOUSEHOLD_1_520_WI_2_evaluation',
 'HOBBIES_2_022_CA_4_evaluation',
 'FOODS_2_391_WI_1_evaluation',
 'FOODS_1_045_TX_3_evaluation',
 'FOODS_1_104_WI_2_evaluation',
 'HOUSEHOLD_1_345_CA_4_evaluation',
 'HOUSEHOLD_2_069_CA_2_evaluation',
 'HOUSEHOLD_1_510_CA_2_evaluation',
 'HOUSEHOLD_2_109_CA_1_evaluation',
 'HOUSEHOLD_2_011_CA_1_evaluation',
 'HOUSEHOLD_1_526_CA_2_evaluation',
 'HOBBIES_1_316_CA_4_evaluation',
 'FOODS_2_347_CA_4_evaluation',
 'FOODS_3_501_CA_4_evaluation',
 'HOUSEHOLD_1_399_CA_2_evaluation',
 'FOODS_2_082_WI_2_evaluation',
 'FOODS_2_182_CA_3_evaluation',
 'HOBBIES_1_423_CA_4_evaluation',
 'HOUSEHOLD_1_012_TX_2_evaluation',
 'FOODS_3_620_WI_3_evaluation',
 'FOODS_3_172_TX_2_evaluation',
 'FOODS_2_064_WI_2_evaluation',
 'FOODS_3_165_WI_1_evaluation',
 'HOUSEHOLD_2_028_WI_3_evaluation',
 'HOUSEHOLD_2_022_CA_2_evaluation',
 'HOUSEHOLD_2_199_CA_3_evaluation',
 'HOUSEHOLD_1_296_CA_4_evaluation',
 'FOODS_3_795_CA_1_evaluation',
 'HOBBIES_1_253_CA_4_evaluation',
 'HOUSEHOLD_2_340_TX_2_evaluation',
 'FOODS_2_353_TX_2_evaluation',
 'HOUSEHOLD_1_120_CA_2_evaluation',
 'FOODS_3_444_CA_1_evaluation',
 'FOODS_3_169_WI_2_evaluation',
 'FOODS_2_179_CA_3_evaluation',
 'FOODS_3_319_WI_2_evaluation',
 'HOBBIES_2_116_CA_3_evaluation',
 'FOODS_2_077_TX_3_evaluation',
 'FOODS_3_726_CA_1_evaluation',
 'FOODS_2_281_TX_1_evaluation',
 'FOODS_1_157_TX_1_evaluation',
 'HOBBIES_1_322_CA_4_evaluation',
 'HOBBIES_1_253_TX_2_evaluation',
 'HOUSEHOLD_2_468_TX_3_evaluation',
 'HOUSEHOLD_2_376_CA_1_evaluation',
 'FOODS_3_325_CA_3_evaluation',
 'HOUSEHOLD_2_416_TX_3_evaluation',
 'HOBBIES_2_064_CA_2_evaluation',
 'HOUSEHOLD_1_430_CA_1_evaluation',
 'FOODS_3_721_WI_2_evaluation',
 'FOODS_3_545_WI_1_evaluation',
 'HOUSEHOLD_2_030_CA_2_evaluation',
 'HOBBIES_1_290_TX_2_evaluation',
 'HOBBIES_1_352_WI_2_evaluation',
 'HOUSEHOLD_2_464_CA_1_evaluation',
 'HOUSEHOLD_1_024_CA_3_evaluation',
 'FOODS_3_202_CA_3_evaluation',
 'FOODS_3_628_CA_3_evaluation',
 'HOUSEHOLD_2_374_CA_4_evaluation',
 'HOUSEHOLD_1_328_CA_2_evaluation',
 'FOODS_3_764_WI_2_evaluation',
 'HOBBIES_1_019_TX_1_evaluation',
 'FOODS_3_813_TX_1_evaluation',
 'FOODS_2_081_TX_3_evaluation',
 'HOUSEHOLD_1_498_TX_2_evaluation',
 'HOUSEHOLD_2_431_WI_2_evaluation',
 'HOBBIES_1_112_TX_1_evaluation',
 'HOUSEHOLD_1_323_WI_1_evaluation',
 'FOODS_2_398_TX_2_evaluation',
 'HOBBIES_1_174_WI_3_evaluation',
 'FOODS_3_637_TX_3_evaluation',
 'FOODS_2_239_CA_4_evaluation',
 'HOUSEHOLD_2_075_TX_2_evaluation',
 'HOBBIES_1_216_WI_1_evaluation',
 'FOODS_2_028_WI_2_evaluation',
 'FOODS_1_175_CA_4_evaluation',
 'FOODS_3_083_CA_1_evaluation',
 'FOODS_1_012_CA_4_evaluation',
 'FOODS_3_270_WI_3_evaluation',
 'FOODS_3_522_CA_2_evaluation',
 'FOODS_3_236_TX_3_evaluation',
 'HOUSEHOLD_1_432_TX_3_evaluation',
 'FOODS_3_563_WI_1_evaluation',
 'HOUSEHOLD_1_524_CA_1_evaluation',
 'FOODS_1_179_CA_1_evaluation',
 'HOUSEHOLD_2_091_WI_1_evaluation',
 'FOODS_1_113_WI_1_evaluation',
 'HOUSEHOLD_2_388_WI_1_evaluation',
 'HOBBIES_2_011_WI_2_evaluation',
 'FOODS_3_760_CA_2_evaluation',
 'HOBBIES_1_399_CA_4_evaluation',
 'HOUSEHOLD_2_222_CA_4_evaluation',
 'FOODS_2_121_CA_2_evaluation',
 'HOBBIES_1_036_CA_4_evaluation',
 'HOUSEHOLD_2_089_CA_3_evaluation',
 'HOUSEHOLD_1_078_WI_1_evaluation',
 'HOBBIES_1_167_TX_3_evaluation',
 'HOBBIES_1_073_CA_1_evaluation',
 'FOODS_3_229_TX_3_evaluation',
 'HOBBIES_2_018_CA_4_evaluation',
 'HOUSEHOLD_1_118_CA_2_evaluation',
 'FOODS_1_170_CA_3_evaluation',
 'FOODS_3_224_CA_2_evaluation',
 'HOUSEHOLD_2_392_CA_2_evaluation',
 'HOUSEHOLD_2_243_CA_2_evaluation',
 'FOODS_3_645_CA_2_evaluation',
 'HOUSEHOLD_2_044_CA_3_evaluation',
 'HOBBIES_1_227_TX_1_evaluation',
 'HOBBIES_2_034_WI_3_evaluation',
 'HOUSEHOLD_2_371_TX_1_evaluation',
 'HOUSEHOLD_1_428_WI_1_evaluation',
 'HOUSEHOLD_1_314_WI_1_evaluation',
 'HOBBIES_1_271_TX_2_evaluation',
 'FOODS_3_824_TX_3_evaluation',
 'HOUSEHOLD_2_324_CA_2_evaluation',
 'HOBBIES_1_229_TX_2_evaluation',
 'HOUSEHOLD_1_526_TX_2_evaluation',
 'FOODS_2_244_CA_3_evaluation',
 'FOODS_3_742_TX_1_evaluation',
 'HOUSEHOLD_2_080_CA_3_evaluation',
 'FOODS_3_156_WI_3_evaluation',
 'HOUSEHOLD_2_411_CA_3_evaluation',
 'HOBBIES_2_051_WI_3_evaluation',
 'FOODS_3_395_CA_1_evaluation',
 'HOUSEHOLD_2_254_TX_3_evaluation',
 'HOUSEHOLD_1_050_TX_2_evaluation',
 'HOUSEHOLD_1_482_CA_4_evaluation',
 'FOODS_2_130_WI_2_evaluation',
 'HOBBIES_1_416_WI_2_evaluation',
 'HOBBIES_1_411_CA_2_evaluation',
 'FOODS_1_150_TX_3_evaluation',
 'HOBBIES_2_043_TX_1_evaluation',
 'FOODS_3_382_TX_2_evaluation',
 'FOODS_2_014_CA_3_evaluation',
 'FOODS_3_523_WI_1_evaluation',
 'FOODS_2_222_TX_2_evaluation',
 'FOODS_2_372_TX_2_evaluation',
 'FOODS_3_801_CA_2_evaluation',
 'FOODS_3_140_CA_4_evaluation',
 'HOUSEHOLD_1_259_WI_1_evaluation',
 'HOBBIES_1_115_CA_2_evaluation',
 'HOUSEHOLD_2_297_CA_4_evaluation',
 'FOODS_3_036_CA_4_evaluation',
 'FOODS_1_197_CA_2_evaluation',
 'FOODS_3_297_WI_2_evaluation',
 'FOODS_1_090_CA_2_evaluation',
 'FOODS_3_631_WI_3_evaluation',
 'HOUSEHOLD_1_214_CA_3_evaluation',
 'FOODS_2_342_CA_3_evaluation',
 'FOODS_3_647_TX_3_evaluation',
 'HOBBIES_1_328_TX_1_evaluation',
 'FOODS_1_064_TX_2_evaluation',
 'FOODS_2_108_CA_4_evaluation',
 'HOBBIES_1_275_WI_1_evaluation',
 'HOBBIES_2_061_CA_3_evaluation',
 'FOODS_1_185_CA_2_evaluation',
 'HOUSEHOLD_2_450_TX_3_evaluation',
 'HOUSEHOLD_2_330_WI_3_evaluation',
 'FOODS_1_062_WI_3_evaluation',
 'HOUSEHOLD_2_170_CA_1_evaluation',
 'FOODS_2_105_TX_1_evaluation',
 'HOUSEHOLD_1_143_TX_1_evaluation',
 'FOODS_3_514_WI_3_evaluation',
 'HOBBIES_1_172_CA_1_evaluation',
 'FOODS_3_722_CA_1_evaluation',
 'HOUSEHOLD_1_027_WI_3_evaluation',
 'HOUSEHOLD_2_077_TX_2_evaluation',
 'FOODS_3_765_CA_2_evaluation',
 'FOODS_3_205_WI_1_evaluation',
 'HOUSEHOLD_2_304_WI_2_evaluation',
 'FOODS_3_326_CA_4_evaluation',
 'FOODS_3_422_TX_3_evaluation',
 'FOODS_3_222_WI_1_evaluation',
 'FOODS_2_005_CA_2_evaluation',
 'HOBBIES_2_056_CA_4_evaluation',
 'HOUSEHOLD_1_399_TX_3_evaluation',
 'HOUSEHOLD_1_110_TX_2_evaluation',
 'HOBBIES_1_175_CA_1_evaluation',
 'HOBBIES_1_067_TX_3_evaluation',
 'HOUSEHOLD_2_504_TX_3_evaluation',
 'HOUSEHOLD_2_095_TX_1_evaluation',
 'HOBBIES_1_413_TX_1_evaluation',
 'FOODS_2_010_TX_3_evaluation',
 'HOUSEHOLD_1_406_CA_4_evaluation',
 'FOODS_3_137_CA_4_evaluation',
 'HOUSEHOLD_2_322_WI_1_evaluation',
 'FOODS_1_135_TX_3_evaluation',
 'FOODS_3_521_WI_2_evaluation',
 'HOUSEHOLD_2_116_TX_2_evaluation',
 'FOODS_3_814_WI_2_evaluation',
 'HOUSEHOLD_2_202_CA_2_evaluation',
 'HOUSEHOLD_1_055_TX_1_evaluation',
 'FOODS_2_244_CA_1_evaluation',
 'FOODS_3_405_CA_4_evaluation',
 'HOBBIES_1_058_CA_4_evaluation',
 'HOUSEHOLD_2_224_CA_1_evaluation',
 'FOODS_2_278_CA_4_evaluation',
 'HOBBIES_2_102_CA_2_evaluation',
 'FOODS_1_129_CA_1_evaluation',
 'FOODS_3_087_TX_1_evaluation',
 'HOUSEHOLD_2_315_TX_3_evaluation',
 'HOUSEHOLD_1_399_TX_1_evaluation',
 'FOODS_3_736_TX_2_evaluation',
 'FOODS_3_730_CA_4_evaluation',
 'HOUSEHOLD_1_097_WI_2_evaluation',
 'HOUSEHOLD_1_408_TX_3_evaluation',
 'HOUSEHOLD_1_347_CA_2_evaluation',
 'HOUSEHOLD_2_206_CA_1_evaluation',
 'FOODS_1_128_WI_1_evaluation',
 'FOODS_3_613_WI_1_evaluation',
 'HOBBIES_1_315_TX_1_evaluation',
 'HOUSEHOLD_2_333_TX_2_evaluation',
 'HOBBIES_1_197_WI_3_evaluation',
 'HOBBIES_1_104_WI_1_evaluation',
 'FOODS_3_516_TX_3_evaluation',
 'FOODS_3_388_WI_3_evaluation',
 'HOUSEHOLD_2_395_TX_2_evaluation',
 'FOODS_2_063_CA_2_evaluation',
 'HOBBIES_1_347_TX_1_evaluation',
 'FOODS_1_093_WI_1_evaluation',
 'HOBBIES_1_352_TX_2_evaluation',
 'FOODS_3_023_WI_1_evaluation',
 'FOODS_2_020_WI_2_evaluation',
 'HOUSEHOLD_2_310_CA_4_evaluation',
 'HOBBIES_1_333_TX_1_evaluation',
 'FOODS_3_248_WI_2_evaluation',
 'FOODS_2_287_WI_1_evaluation',
 'HOBBIES_2_008_WI_3_evaluation',
 'HOUSEHOLD_2_043_WI_2_evaluation',
 'FOODS_3_380_TX_1_evaluation',
 'FOODS_3_053_TX_2_evaluation',
 'HOBBIES_2_104_WI_2_evaluation',
 'FOODS_3_813_WI_1_evaluation',
 'FOODS_3_160_CA_4_evaluation',
 'FOODS_3_404_TX_3_evaluation',
 'FOODS_2_315_CA_1_evaluation',
 'FOODS_3_460_WI_2_evaluation',
 'FOODS_2_194_CA_2_evaluation',
 'FOODS_2_195_TX_2_evaluation',
 'HOUSEHOLD_1_076_WI_1_evaluation',
 'HOUSEHOLD_2_192_CA_4_evaluation',
 'FOODS_3_821_CA_2_evaluation',
 'FOODS_3_023_CA_2_evaluation',
 'FOODS_3_582_CA_4_evaluation',
 'FOODS_3_482_WI_1_evaluation',
 'HOUSEHOLD_2_189_WI_3_evaluation',
 'FOODS_3_414_CA_3_evaluation',
 'FOODS_3_201_CA_2_evaluation',
 'HOUSEHOLD_1_063_WI_1_evaluation',
 'HOUSEHOLD_2_264_CA_4_evaluation',
 'FOODS_3_297_CA_1_evaluation',
 'HOBBIES_2_103_WI_3_evaluation',
 'HOBBIES_2_083_CA_1_evaluation',
 'FOODS_1_198_WI_2_evaluation',
 'HOUSEHOLD_1_346_WI_2_evaluation',
 'FOODS_3_499_WI_3_evaluation',
 'HOUSEHOLD_1_053_WI_1_evaluation',
 'HOUSEHOLD_1_149_TX_3_evaluation',
 'HOBBIES_2_121_TX_3_evaluation',
 'HOUSEHOLD_2_163_CA_2_evaluation',
 'HOBBIES_1_159_TX_1_evaluation',
 'HOUSEHOLD_2_157_WI_3_evaluation',
 'HOUSEHOLD_1_365_WI_2_evaluation',
 'FOODS_1_069_TX_3_evaluation',
 'HOBBIES_1_073_WI_3_evaluation',
 'HOUSEHOLD_1_062_CA_3_evaluation',
 'FOODS_2_006_TX_2_evaluation',
 'FOODS_3_705_CA_1_evaluation',
 'FOODS_3_374_TX_1_evaluation',
 'FOODS_3_029_CA_2_evaluation',
 'HOBBIES_1_021_WI_2_evaluation',
 'HOUSEHOLD_2_116_CA_1_evaluation',
 'FOODS_1_001_TX_2_evaluation',
 'FOODS_2_270_CA_4_evaluation',
 'FOODS_2_189_CA_1_evaluation',
 'FOODS_3_814_TX_3_evaluation',
 'HOUSEHOLD_2_021_CA_2_evaluation',
 'FOODS_3_186_WI_3_evaluation',
 'HOBBIES_1_065_TX_3_evaluation',
 'FOODS_2_085_TX_3_evaluation',
 'HOBBIES_1_299_CA_2_evaluation',
 'FOODS_3_428_TX_3_evaluation',
 'FOODS_3_786_TX_2_evaluation',
 'HOBBIES_1_399_TX_2_evaluation',
 'FOODS_1_136_TX_1_evaluation',
 'FOODS_3_189_TX_1_evaluation',
 'HOUSEHOLD_1_255_CA_2_evaluation',
 'HOUSEHOLD_2_242_TX_1_evaluation',
 'FOODS_3_441_TX_2_evaluation',
 'FOODS_2_226_WI_2_evaluation',
 'HOUSEHOLD_1_040_CA_1_evaluation',
 'HOUSEHOLD_1_341_CA_4_evaluation',
 'FOODS_3_440_CA_2_evaluation',
 'FOODS_1_040_CA_2_evaluation',
 'FOODS_3_006_TX_3_evaluation',
 'FOODS_2_120_CA_2_evaluation',
 'HOUSEHOLD_1_147_WI_1_evaluation',
 'HOBBIES_2_038_WI_3_evaluation',
 'HOUSEHOLD_2_359_TX_1_evaluation',
 'HOUSEHOLD_2_511_CA_1_evaluation',
 'FOODS_2_313_CA_2_evaluation',
 'HOUSEHOLD_2_318_TX_1_evaluation',
 'HOBBIES_1_124_WI_2_evaluation',
 'HOUSEHOLD_2_028_TX_2_evaluation',
 'FOODS_1_052_CA_4_evaluation',
 'FOODS_2_008_WI_3_evaluation',
 'HOUSEHOLD_2_106_TX_3_evaluation',
 'HOBBIES_1_130_CA_3_evaluation',
 'FOODS_3_118_CA_3_evaluation',
 'HOBBIES_1_039_TX_3_evaluation',
 'FOODS_2_190_WI_3_evaluation',
 'HOBBIES_1_307_WI_1_evaluation',
 'FOODS_3_556_WI_2_evaluation',
 'FOODS_3_795_WI_3_evaluation',
 'FOODS_1_121_CA_1_evaluation',
 'HOUSEHOLD_2_349_TX_3_evaluation',
 'HOBBIES_1_126_CA_3_evaluation',
 'FOODS_3_094_TX_3_evaluation',
 'FOODS_1_143_CA_2_evaluation',
 'FOODS_3_271_TX_1_evaluation',
 'FOODS_3_430_WI_2_evaluation',
 'HOBBIES_1_236_CA_3_evaluation',
 'HOUSEHOLD_1_204_CA_2_evaluation',
 'HOUSEHOLD_2_302_CA_3_evaluation',
 'FOODS_3_150_WI_2_evaluation',
 'FOODS_3_074_WI_1_evaluation',
 'FOODS_3_584_WI_2_evaluation',
 'HOBBIES_2_142_CA_2_evaluation',
 'FOODS_1_177_WI_3_evaluation',
 'FOODS_3_805_CA_1_evaluation',
 'HOBBIES_1_399_WI_1_evaluation',
 'HOUSEHOLD_1_108_CA_1_evaluation',
 'FOODS_1_206_TX_2_evaluation',
 'HOUSEHOLD_2_480_CA_2_evaluation',
 'HOBBIES_1_312_WI_1_evaluation',
 'FOODS_3_259_WI_3_evaluation',
 'HOBBIES_1_022_CA_3_evaluation',
 'HOUSEHOLD_2_171_CA_4_evaluation',
 'HOUSEHOLD_1_494_TX_2_evaluation',
 'HOUSEHOLD_1_336_CA_4_evaluation',
 'FOODS_3_385_CA_1_evaluation',
 'HOBBIES_1_254_WI_3_evaluation',
 'HOUSEHOLD_1_076_TX_2_evaluation',
 'HOUSEHOLD_2_199_WI_3_evaluation',
 'HOUSEHOLD_1_087_TX_3_evaluation',
 'HOUSEHOLD_1_047_TX_2_evaluation',
 'HOUSEHOLD_2_088_CA_3_evaluation',
 'HOBBIES_1_089_CA_4_evaluation',
 'FOODS_3_605_CA_3_evaluation',
 'FOODS_2_064_CA_1_evaluation',
 'FOODS_2_171_CA_3_evaluation',
 'HOUSEHOLD_1_524_CA_4_evaluation',
 'FOODS_3_510_CA_4_evaluation',
 'FOODS_3_584_TX_3_evaluation',
 'HOUSEHOLD_1_514_TX_3_evaluation',
 'FOODS_3_251_CA_3_evaluation',
 'FOODS_2_156_WI_1_evaluation',
 'HOBBIES_1_083_CA_4_evaluation',
 'HOUSEHOLD_2_361_TX_3_evaluation',
 'HOUSEHOLD_1_527_TX_1_evaluation',
 'HOBBIES_1_350_TX_2_evaluation',
 'FOODS_3_075_TX_1_evaluation',
 'FOODS_2_155_TX_3_evaluation',
 'FOODS_1_087_WI_2_evaluation',
 'HOUSEHOLD_2_309_CA_4_evaluation',
 'HOUSEHOLD_1_451_WI_3_evaluation',
 'HOUSEHOLD_1_389_WI_2_evaluation',
 'FOODS_3_043_CA_2_evaluation',
 'FOODS_3_229_CA_4_evaluation',
 'FOODS_3_536_TX_1_evaluation',
 'FOODS_3_176_WI_3_evaluation',
 'HOUSEHOLD_1_365_CA_3_evaluation',
 'HOBBIES_1_084_TX_1_evaluation',
 'HOBBIES_1_205_WI_3_evaluation',
 'FOODS_3_634_TX_1_evaluation',
 'FOODS_3_581_CA_4_evaluation',
 'FOODS_3_045_TX_2_evaluation',
 'FOODS_3_590_CA_3_evaluation',
 'HOUSEHOLD_2_135_WI_1_evaluation',
 'HOBBIES_1_184_WI_2_evaluation',
 'HOUSEHOLD_2_492_CA_1_evaluation',
 'FOODS_2_251_CA_4_evaluation',
 'FOODS_3_086_CA_1_evaluation',
 'FOODS_3_213_WI_3_evaluation',
 'FOODS_2_136_TX_3_evaluation',
 'HOUSEHOLD_2_236_CA_4_evaluation',
 'FOODS_1_062_WI_1_evaluation',
 'HOUSEHOLD_1_156_TX_1_evaluation',
 'FOODS_3_734_WI_1_evaluation',
 'HOUSEHOLD_2_351_TX_2_evaluation',
 'FOODS_1_135_TX_2_evaluation',
 'FOODS_1_215_CA_1_evaluation',
 'HOUSEHOLD_1_286_TX_3_evaluation',
 'FOODS_3_681_CA_1_evaluation',
 'FOODS_2_114_WI_2_evaluation',
 'HOBBIES_2_125_CA_2_evaluation',
 'HOBBIES_2_061_CA_2_evaluation',
 'HOUSEHOLD_2_009_TX_3_evaluation',
 'HOUSEHOLD_2_382_CA_1_evaluation',
 'FOODS_3_794_WI_1_evaluation',
 'FOODS_2_109_CA_4_evaluation',
 'HOBBIES_1_080_CA_4_evaluation',
 'HOUSEHOLD_1_411_WI_2_evaluation',
 'HOUSEHOLD_1_005_WI_3_evaluation',
 'FOODS_1_180_TX_2_evaluation',
 'HOUSEHOLD_2_216_CA_4_evaluation',
 'FOODS_2_151_CA_1_evaluation',
 'HOBBIES_1_145_WI_2_evaluation',
 'HOBBIES_1_061_CA_1_evaluation',
 'FOODS_3_082_WI_2_evaluation',
 'HOUSEHOLD_1_430_WI_2_evaluation',
 'FOODS_3_212_TX_2_evaluation',
 'HOBBIES_1_313_WI_3_evaluation',
 'HOUSEHOLD_2_399_WI_1_evaluation',
 'HOBBIES_1_358_WI_2_evaluation',
 'FOODS_3_482_TX_1_evaluation',
 'HOUSEHOLD_2_154_WI_2_evaluation',
 'HOBBIES_1_119_TX_1_evaluation',
 'FOODS_3_356_CA_2_evaluation',
 'FOODS_2_129_CA_1_evaluation',
 'HOUSEHOLD_1_209_CA_3_evaluation',
 'FOODS_1_140_WI_3_evaluation',
 'FOODS_3_343_CA_2_evaluation',
 'HOUSEHOLD_2_141_WI_1_evaluation',
 'FOODS_1_189_CA_2_evaluation',
 'HOBBIES_1_105_WI_2_evaluation',
 'FOODS_3_387_CA_1_evaluation',
 'HOBBIES_1_139_TX_3_evaluation',
 'FOODS_3_751_WI_1_evaluation',
 'HOUSEHOLD_2_289_WI_1_evaluation',
 'HOUSEHOLD_1_525_CA_4_evaluation',
 'HOUSEHOLD_1_394_CA_1_evaluation',
 'HOBBIES_1_215_TX_2_evaluation',
 'HOUSEHOLD_2_266_CA_4_evaluation',
 'HOUSEHOLD_2_023_WI_1_evaluation',
 'HOBBIES_1_002_TX_1_evaluation',
 'FOODS_1_057_TX_3_evaluation',
 'HOUSEHOLD_1_172_WI_1_evaluation',
 'HOUSEHOLD_2_390_TX_1_evaluation',
 'HOUSEHOLD_2_196_TX_1_evaluation',
 'FOODS_3_125_CA_1_evaluation',
 'HOUSEHOLD_2_101_WI_2_evaluation',
 'HOUSEHOLD_2_210_WI_1_evaluation',
 'HOUSEHOLD_2_324_WI_2_evaluation',
 'HOBBIES_2_003_CA_2_evaluation',
 'HOUSEHOLD_1_110_CA_1_evaluation',
 'HOBBIES_1_117_CA_1_evaluation',
 'HOBBIES_1_074_TX_1_evaluation',
 'HOUSEHOLD_1_234_CA_3_evaluation',
 'FOODS_2_308_CA_4_evaluation',
 'FOODS_3_437_TX_1_evaluation',
 'HOUSEHOLD_1_010_CA_4_evaluation',
 'HOUSEHOLD_1_236_WI_1_evaluation',
 'FOODS_3_805_WI_1_evaluation',
 'FOODS_3_609_WI_1_evaluation',
 'FOODS_2_352_WI_2_evaluation',
 'FOODS_3_621_WI_3_evaluation',
 'FOODS_2_017_TX_3_evaluation',
 'FOODS_1_157_CA_2_evaluation',
 'HOUSEHOLD_1_211_CA_2_evaluation',
 'FOODS_1_218_TX_1_evaluation',
 'HOBBIES_1_370_CA_2_evaluation',
 'FOODS_3_057_TX_1_evaluation',
 'HOUSEHOLD_1_332_TX_1_evaluation',
 'FOODS_2_293_CA_3_evaluation',
 'HOUSEHOLD_1_059_CA_2_evaluation',
 'HOUSEHOLD_2_040_CA_1_evaluation',
 'FOODS_3_578_WI_1_evaluation',
 'HOUSEHOLD_1_189_TX_1_evaluation',
 'HOUSEHOLD_1_040_WI_2_evaluation',
 'HOUSEHOLD_1_206_TX_1_evaluation',
 'HOUSEHOLD_2_178_CA_1_evaluation',
 'HOBBIES_1_073_CA_2_evaluation',
 'FOODS_3_055_CA_2_evaluation',
 'FOODS_3_218_TX_3_evaluation',
 'HOUSEHOLD_1_408_WI_2_evaluation',
 'HOUSEHOLD_1_343_WI_3_evaluation',
 'FOODS_3_077_CA_2_evaluation',
 'FOODS_3_495_WI_2_evaluation',
 'HOUSEHOLD_1_187_CA_1_evaluation',
 'HOUSEHOLD_1_440_TX_2_evaluation',
 'HOUSEHOLD_1_061_WI_2_evaluation',
 'FOODS_2_379_TX_3_evaluation',
 'FOODS_1_195_WI_2_evaluation',
 'FOODS_3_301_CA_4_evaluation',
 'HOBBIES_1_223_CA_1_evaluation',
 'HOBBIES_1_166_WI_2_evaluation',
 'HOUSEHOLD_2_498_TX_1_evaluation',
 'FOODS_3_531_CA_1_evaluation',
 'FOODS_3_753_TX_2_evaluation',
 'HOBBIES_1_405_WI_3_evaluation',
 'HOBBIES_2_090_CA_2_evaluation',
 'HOBBIES_1_376_WI_3_evaluation',
 'HOBBIES_1_191_WI_3_evaluation',
 'HOUSEHOLD_2_071_CA_1_evaluation',
 'FOODS_2_032_CA_3_evaluation',
 'HOBBIES_1_418_CA_4_evaluation',
 'FOODS_2_099_WI_2_evaluation',
 'FOODS_3_021_CA_3_evaluation',
 'HOUSEHOLD_1_044_CA_3_evaluation',
 'HOUSEHOLD_2_143_CA_3_evaluation',
 'HOUSEHOLD_2_160_TX_1_evaluation',
 'FOODS_3_236_CA_4_evaluation',
 'HOUSEHOLD_2_372_CA_3_evaluation',
 'HOBBIES_1_354_CA_2_evaluation',
 'HOUSEHOLD_2_293_TX_1_evaluation',
 'HOUSEHOLD_1_294_CA_4_evaluation',
 'FOODS_2_068_CA_4_evaluation',

In [36]:
sales.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4

In [38]:
sales[sales.id == 'FOODS_3_156_WI_3_validation']

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
29821,FOODS_3_156_WI_3_validation,FOODS_3_156,FOODS_3,FOODS,WI_3,WI,3,5,1,3,...,0,3,1,0,2,0,0,4,2,0

In [45]:
calendar.head(10)

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1
5,2011-02-03,11101,Thursday,6,2,2011,d_6,NaN,NaN,NaN,NaN,1,1,1
6,2011-02-04,11101,Friday,7,2,2011,d_7,NaN,NaN,NaN,NaN,1,0,0
7,2011-02-05,11102,Saturday,1,2,2011,d_8,NaN,NaN,NaN,NaN,1,1,1
8,2011-02-06,11102,Sunday,2,2,2011,d_9,SuperBowl,Sporting,NaN,NaN,1,1,1
9,2011-02-07,11102,Monday,3,2,2011,d_10,NaN,NaN,NaN,NaN,1,1,0

# 特征工程

特征工程可以考虑一些交互。首先是不会变动的固有属性，比如二级分类，一级分类，商店，州。从时间维度，我们可以考虑当天、前4周同样的天（比如当天是周一，考虑前四周的周一）、前7天、前30天。从商品的维度，我们考虑按照商品id、该商店该二级品类、该商店该一级品类、商店来进行汇总，之后可以考虑其他店铺或者从州的层面进行汇总。从特殊时间的角度出发，我们可以根据日历统计当天的节日名字，节日类型。还可以考虑距离下一个节日的日期，节日的名字和类型。因为这是从日历获取的内容，所以不算是信息穿越。当天该州的SNAP是否开放。从价格角度，可以考虑前几天是否有提高价格和降低价格行为。
1. 固有属性
    - dept_id
    - cat_id
    - store_id
    - state_id
2. 当天特征
    - price
    - 前七天价格变动幅度
    - 年份
    - 月份
    - 一年的第几个周
    - wm_yr_week是自增序列
    - 当天节日名字
    - 当天节日类型
    - 距离下一个节日的时间
    - 下一个节日的名字
    - 下一个节日的类型
    - snap信息
3. 前一段时间的特征（7天，30天，前4周同一个周天）。统计平均值，标准差，中位数，上升下降的趋势slope
    -  商品销量
    -  店铺销量
    -  品类销量
    -  其他竞品的销量

4. 跨年特征（去年同期连续7天，去年同期周围7周的同一个周天）
    - 商品销量
    - 店铺销量
    - 品类销量
    - 其他竞品销量

没有考虑到的是，需要考虑一些百分比的特征。是否下雨和极端气温也是影响购买的因素，需要外部的数据。以上模型带有的日期其实都是超参数，可以进行调节，但是模型似乎过度复杂了。另一方面，考虑对每天的特征进行指数平滑，越近的样本点权重越大，从而提取新的特征。指数平滑中也有衰减参数，需要进行调整，可能每个大类的衰减参数大小不一样，要分开调整。

# modeling